"""Base strategy classes and signal types for the Binance Quant system."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional

import pandas as pd
import numpy as np


class SignalType(Enum):
    """Types of trading signals a strategy can generate."""
    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    HOLD = "HOLD"


@dataclass
class Signal:
    """A trading signal generated by a strategy.

    Attributes:
        type: The type of signal (LONG, SHORT, CLOSE_LONG, etc.)
        symbol: Trading symbol (e.g., 'BTC/USDT')
        price: Entry/exit price (NaN if using market order)
        quantity: Position size in base asset
        stop_loss: Stop loss price level
        take_profit: Take profit price level
        reason: Human-readable reason for the signal
        confidence: Confidence score 0.0-1.0
        leverage: Leverage multiplier
        strategy_name: Name of the strategy that generated this signal
        timestamp: When the signal was generated
    """
    type: SignalType
    symbol: str
    price: float = float("nan")
    quantity: float = 0.0
    stop_loss: float = float("nan")
    take_profit: float = float("nan")
    reason: str = ""
    confidence: float = 1.0
    leverage: int = 1
    strategy_name: str = ""
    timestamp: Optional[pd.Timestamp] = None

    def to_dict(self) -> dict:
        """Convert signal to a plain dictionary."""
        return {
            "type": self.type.value,
            "symbol": self.symbol,
            "price": self.price,
            "quantity": self.quantity,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "reason": self.reason,
            "confidence": self.confidence,
            "leverage": self.leverage,
            "strategy_name": self.strategy_name,
            "timestamp": str(self.timestamp) if self.timestamp else None,
        }

    def __repr__(self) -> str:
        return (
            f"Signal(type={self.type.value}, symbol={self.symbol}, "
            f"price={self.price:.2f}, qty={self.quantity:.4f}, "
            f"sl={self.stop_loss:.2f}, tp={self.take_profit:.2f}, "
            f"reason='{self.reason}')"
        )


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement generate_signal() and should set self.params
    in __init__. The strategy receives OHLCV data via feed_data() and
    produces trading signals via generate_signal().

    Internal position tracking:
    - _positions: dict mapping symbol -> dict with side/entry_price/qty
    - _data: dict mapping (symbol, timeframe) -> DataFrame
    """

    def __init__(self, name: str, symbols: List[str], timeframes: List[str]):
        self.name = name
        self.symbols = symbols
        self.timeframes = timeframes
        self.params: dict = {}

        # Internal state
        self._data: Dict[tuple, pd.DataFrame] = {}
        self._positions: Dict[str, dict] = {}
        self._indicators: Dict[str, pd.DataFrame] = {}
        self._bars_since_last_trade: int = 999  # ready to trade immediately

    def feed_data(self, symbol: str, timeframe: str, df: pd.DataFrame):
        """Receive kline (OHLCV) data for a symbol/timeframe pair.

        The DataFrame is stored internally; strategies should override
        _preprocess() to compute indicators when data arrives.

        Args:
            symbol: Trading symbol (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '15m', '1h')
            df: DataFrame with columns: open, high, low, close, volume
        """
        self._data[(symbol, timeframe)] = df.copy()
        self._preprocess(symbol, timeframe, df)

    def _preprocess(self, symbol: str, timeframe: str, df: pd.DataFrame):
        """Override in subclasses to compute indicators on data arrival.

        The base implementation is a no-op. Subclasses should compute
        their indicators here and store them in self._indicators,
        keyed by (symbol, timeframe).
        """
        pass

    @abstractmethod
    def generate_signal(self, symbol: str) -> Signal:
        """Generate a trading signal for the given symbol.

        Must be implemented by concrete strategies. Returns a Signal
        with type=HOLD if no action is recommended.

        Args:
            symbol: Trading symbol to generate signal for

        Returns:
            Signal with the recommended action
        """
        ...

    def on_order_filled(self, symbol: str, side: str, price: float, qty: float):
        """Called when an order generated by this strategy is filled.

        Updates internal position tracking.

        Args:
            symbol: Trading symbol
            side: 'buy' or 'sell'
            price: Fill price
            qty: Fill quantity (positive)
        """
        if side == "buy":
            self._positions[symbol] = {
                "side": "LONG",
                "entry_price": price,
                "quantity": qty,
            }
        elif side == "sell":
            if symbol in self._positions:
                del self._positions[symbol]

    def has_position(self, symbol: str) -> bool:
        """Check if this strategy has an open position on the symbol."""
        return symbol in self._positions

    def get_position(self, symbol: str) -> Optional[dict]:
        """Return position details or None."""
        return self._positions.get(symbol)

    def get_required_data(self) -> dict:
        """Return the data requirements for this strategy.

        Returns:
            dict with keys:
                symbols: list of symbols needed
                timeframes: list of timeframes per symbol
                lookback_bars: minimum number of candles needed
        """
        return {
            "symbols": self.symbols,
            "timeframes": self.timeframes,
            "lookback_bars": 100,
        }

    def get_data(self, symbol: str, timeframe: Optional[str] = None) -> Optional[pd.DataFrame]:
        """Access stored data for a symbol/timeframe pair.

        If timeframe is None, returns data for the first timeframe.
        """
        if timeframe is None:
            timeframe = self.timeframes[0] if self.timeframes else "15m"
        return self._data.get((symbol, timeframe))

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', symbols={self.symbols})"
